### ISSUE TITLE
Erros when running with other references

### ISSUE THREAD

**Issue by szsctt** [namphuon/ViFi#25]
I would like to run ViFi with a different reference than the one provided (hg19). I concatenated the reference together with the viral sequence, and indexed it.  I provided this index, as well as a list of chromosomes in the reference, to ViFi.  However, it seems like there are some other files required - a bed file with mappability scores, gff files with genes, etc, which aren't currently documented.  These are listed for hg19 in `data_repo/hg19/file_list.txt`:
```
fa_file 		                hg19full.fa
chrLen_file 		            hg19full.fa.fai
duke35_filename 		        wgEncodeDukeMapabilityUniqueness35bp_sorted.bedGraph
mapability_exclude_filename     wgMapabilityExcludable.bed
gene_filename 		            human_hg19_september_2011/Genes_July_2010_hg19.gff
exon_file 		                human_hg19_september_2011/Exon-Intron_July_2010_hg19.gff
oncogene_filename 		        cancer/oncogenes/Census_oncomerge.gff
centromere_filename 		    hg19_centromere.bed
conserved_regions_filename 		conserved.bed #conserved.gain5.bed (readdepth >2 samples in turner controls KT51-59) + lumpy XYM
segdup_filename 		        annotations/hg19GenomicSuperDup.tab
```
The fasta file and index are easy enough, so I made a file with this information for my reference and tried to run ViFi (without HMMs), but I ran into these warnings and errors:
```
WARNING:root:#TIME 0.048	 interval_list: Unable to open interval file "/home/data_repo/test_human/".
WARNING:root:#TIME 0.048	 interval_list: Unable to open interval file "/home/data_repo/test_human/".
WARNING:root:#TIME 0.048	 interval_list: Unable to open interval file "/home/data_repo/test_human/".
WARNING:root:#TIME 0.048	 interval_list: Unable to open interval file "/home/data_repo/test_human/".
WARNING:root:#TIME 0.048	 interval_list: Unable to open interval file "/home/data_repo/test_human/".
WARNING:root:#TIME 0.050	 rep_content: Unable to open mapability file "/home/data_repo/test_human/".
Traceback (most recent call last):
  File "/home/scripts/cluster_trans_new.py", line 161, in <module>
    if hg.interval(a, bamfile=bamFile).rep_content() <= 3 and a.mapq >= 10:
  File "/home/scripts/hg19util.py", line 384, in rep_content
    m = interval(duke35[p])
  File "/home/scripts/hg19util.py", line 172, in __init__
    self.load_line(line, file_format)
  File "/home/scripts/hg19util.py", line 182, in load_line
    if len(line.strip().split()) == 1:
AttributeError: 'list' object has no attribute 'strip'
```
Seems like the issue is something to do with the missing mappability scores, which aren't available for my reference genome.  Are these required for running ViFi, and are there any options for running with a reference for which they aren't available?

**Comment by AEAtkinson** [comment]
This should be addressed.  Here's what I found:

The options object returned from parser.parse_args() belongs to class argparse.Namespace, and has an attribute for every command-line argument that is added through an add_argument call, like “runningOptions.add_argument('--reference', default=default_reference, type=str,…” on line 31. So the options object has a .reference attribute because there is a --reference command-line argument, but there isn’t a --default_reference argument, so there won’t be a .default_reference attribute. Therefore you get an AttributeError.
 
That code has another bug on lines 22 through 25, where the author adds the “Running options” option group on line 22, and then replaces that option group on line 25 with another option group named “Running options”.
